### ISSUE TITLE
usability / readme

### ISSUE THREAD

**Issue by vscooper** [ying14/yingtools2#1]
Hi Ying, we met at the U01 team meeting in AA. Have examined this repo and would benefit from brief instructions about how to run a demo. Can explain why by DM. Thanks

**Comment by ying14** [comment]
Happy to help if I can... my email is taury@mskcc.org if you'd like to discuss.

**Comment by elittmann** [comment]
A readme and tutorial has been added-- this will be expanded on in the coming months
