### ISSUE TITLE
Lefse problem setwd()

### ISSUE THREAD

**Issue by somala05** [ying14/yingtools2#10]
Hi, 
I still have a problem with running the lefse wrapper. I followed the instructions as described here https://github.com/ying14/yingtools2/wiki/Using-the-%60lefse%60-wrapper-function
and set up my workin directory like this setwd("~/Downloads/nsegata-lefse-82605a2ae7b7-3/"). 
But when I try to run lefse in R, like this
lefse.tbl <- lefse(physeq,class="Diagnosis")

I still get this error message 

Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: Column `sample` joining factor and character vector, coercing into character vector 
2: In system(format.command) : error in running command
3: In system(lefse.command) : error in running command
4: In file(file, "rt") :
  cannot open file 'lefse.res': No such file or directory

I have no idea how to solve this problem and would greatly appreciate any suggestions. 
Thank you

**Comment by somala05** [comment]
Actually, I think now it works, but I get still this error by running this:

lefse.tbl <- lefse2(physeq, class="Diagnosis") 

Error in summarize(., pctseqs = sum(pctseqs)) : 
  argument "by" is missing, with no default

**Comment by ying14** [comment]
It could be that you have a namespace conflict and are not using the correct 'summarize' function. You need the one from dplyr. In the lefse2 definition, try changing 'summarize' to 'dplyr::summarize'. I think you might be using the one from the Hmisc package. See if this works.

**Comment by somala05** [comment]
Thank you so much, this already helped, but now I´m getting this error

> lefse.tbl <- lefse2(physeq,class="Diagnosis")

Traceback (most recent call last):
  File "run_lefse.py", line 4, in <module>
    from lefse import *
  File "~/Downloads/nsegata-lefse-82605a2ae7b7-3/", line 3, in <module>
    import rpy2.robjects as robjects
ImportError: No module named rpy2.robjects
[1] "Wrote lefse.res"
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: Column `sample` joining factor and character vector, coercing into character vector 
2: In file(file, "rt") :
 
 Error in file(file, "rt") : cannot open the connection 




Any idea?

**Comment by elittmann** [comment]
It looks like the rpy2 module isn't installed or is a different version than lefse wants... if you open a terminal and run: 
~/Downloads/nsegata-lefse-82605a2ae7b7-3/python format_input.py -h 

Do you get the same error? If so lefse was not installed correctly (it can be difficult to configure on most computers as it uses old versions of modules...)

On newer operating systems I usually need to install lefse using docker

**Comment by NeginValizadegan** [comment]
> It looks like the rpy2 module isn't installed or is a different version than lefse wants... if you open a terminal and run:
> ~/Downloads/nsegata-lefse-82605a2ae7b7-3/python format_input.py -h
> 
> Do you get the same error? If so lefse was not installed correctly (it can be difficult to configure on most computers as it uses old versions of modules...)
> 
> On newer operating systems I usually need to install lefse using docker

I have the same problem but I installed rpy2 several times. I actually searched for it and I have several version of it in different places and for different versions of pythons. Do I have to remove any of these? And if so, does it matter where python and rpy2 are installed? Should they be in the same folder as where lefse zip file is? 

Also, how do I know its version is the same as the one in lefse?

Thanks!
