### ISSUE TITLE
dcast failing to read in phyloseq objects

### ISSUE THREAD

**Issue by liisaveerus** [ying14/yingtools2#11]
Hi,

I am very excited to use your LEfSe wrapper! However, I am running into the same error with my own data and the example data (cid94)---both phyloseq objects:

lala=lefse2(cid.phy, class="Consistency")

Error in UseMethod("dcast", data) : 
no applicable method for 'dcast' applied to an object of class "c('tbl_df', 'tbl', 'data.frame')" 

I have specified the correct working directory, ran the modified function (lefse2), and am stuck at the moment. Would really appreciate your help, thank you!

Liisa

**Comment by ying14** [comment]
Try installing the reshape2 package, dcast comes from that package.
