### ISSUE TITLE
Error with taxon when running LefSe

### ISSUE THREAD

**Issue by dbro970** [ying14/yingtools2#13]
Hi,
Thanks for the great work in this package.

I'm trying to use the LeSe Wrapper code and keep getting the same issue when making the lefse.tbl (including when I use the sample data included in the package)
The error message is: 
" Error in gsub(" ", "_", taxon) : object 'taxon' not found"

Do you have any idea why this might be the case and how I could fix this issue?
Thanks in advance!

**Comment by ying14** [comment]
Any chance you have the plyr package loaded? This might be caused by the function using plyr::summarize instead of dplyr::summarize. Try unloading the plyr package, or change the lefse function to make sure the correct function is used:
```
lefse2 <- function (phy, class, subclass = NA, subject = NA, anova.alpha = 0.05, 
                    wilcoxon.alpha = 0.05, lda.cutoff = 2, wilcoxon.within.subclass = FALSE, 
                    one.against.one = FALSE, mult.test.correction = 0, make.lefse.plots = FALSE, 
                    by_otus = FALSE, levels = rank_names(phy)) { 
  summarize <- dplyr::summarize
  ...
  ...
}
```
