### ISSUE TITLE
Issue in LefseS wrapper function

### ISSUE THREAD

**Issue by marselr2** [ying14/yingtools2#16]
Dear All,

I am having problems with the LESFE analysis from ying14/yingtools2.

I have tried with the lefse2 (modified according to https://github.com/ying14/yingtools2/wiki/Using-the-%60lefse%60-wrapper-function) but It gave me an error.  

I downloaded the Lefse zip and I have the unzipped folder as working directory in R session as the tutorial propose. 

My code and the otuput:
lefse.tbl <- lefse2(data, class="Parto")

 Error in gsub(" ", "_", taxon) : object 'taxon' not found 

Could you help me with that? Any idea?

**I don't know if it would be useful a look of my taxa_table:**

head(tax_table(data))

Taxonomy Table:     [6 taxa by 7 taxonomic ranks]:
     Kingdom    Phylum           Class                 Order               Family              
ASV1 "Bacteria" "Proteobacteria" "Gammaproteobacteria" "Enterobacteriales" "Enterobacteriaceae"
ASV2 "Bacteria" "Actinobacteria" "Actinobacteria"      "Bifidobacteriales" "Bifidobacteriaceae"
ASV3 "Bacteria" "Firmicutes"     "Bacilli"             "Lactobacillales"   "Streptococcaceae"  
ASV4 "Bacteria" "Actinobacteria" "Actinobacteria"      "Bifidobacteriales" "Bifidobacteriaceae"
ASV5 "Bacteria" "Firmicutes"     "Bacilli"             "Lactobacillales"   "Enterococcaceae"   
ASV6 "Bacteria" "Actinobacteria" "Actinobacteria"      "Bifidobacteriales" "Bifidobacteriaceae"
     Genus                  Species  
ASV1 "Escherichia/Shigella" NA       
ASV2 "Bifidobacterium"      "longum" 
ASV3 "Streptococcus"        NA       
ASV4 "Bifidobacterium"      NA       
ASV5 "Enterococcus"         NA       
ASV6 "Bifidobacterium"      "bifidum"

Thank you!

**Comment by ying14** [comment]
Perhaps you've loaded both the `plyr` and `dplyr` package? Both have a function called `summarize`, and in this function you need to use `dplyr::summarize`. More info here about this problem: [https://github.com/tidyverse/dplyr/issues/347](url)

In the `lefse2` function, you could try changing "summarize" to "dplyr::summarize". If that solves the problem, then I think that is the issue. You may want to load `plyr` before `dplyr`, or just stop using `plyr` altogether, to avoid the confusion in the future.

**Comment by marselr2** [comment]
It works! Thank you! I restarted the Rsesion and I only loeaded the dplyr package. 

I'm having now problems with the python scripts. I obtained the lefse.txt file resutled from the first part of the function lefse2, but I got a python type error. 

I think it is becasue I have installed the python 3.0 and the lefse was constructed under python 2.0 and some syntaxis are a bit difference. 
I will try with python 2.0

However, I got my lefse plots by uploading the txt resulted from the function lefse2 in the Galaxy server from The Huttenhower Lab and then plotting the result with the package microbiota.R from wipperman repositorie. 

In that way I can customize the plot. Just, if the explanation could help someone. 

In anyway, thank you very much for your help with the issue.

**Comment by Fla1487** [comment]
Dear all and ying14,

I have followed the instruction for the lefse2, but I have this problem:


> lefse.tbl <- lefse2(phy_obj0,class="HLA3")

C:\Python27\python.exe: can't open file 'format_input.py': [Errno 2] No such file or directory C:\Python27\python.exe: can't open file 'run_lefse.py': [Errno 2] No such file or directory
[1] "Wrote lefse.res"
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: In dcast(., sample ~ taxon, value.var = "pctseqs", fill = 0) :   The dcast generic in data.table has been passed a tbl_df and will attempt to redirect to the reshape2::dcast; please note that reshape2 is deprecated, and this redirection is now deprecated as well. Please do this redirection yourself like reshape2::dcast(.). In the next version, this warning will become an error.
2: Column `sample` joining factor and character vector, coercing into character vector
3: select_() is deprecated.  Please use select() instead  The 'programming' vignette or the tidyeval book can help you to program with select() : https://tidyeval.tidyverse.org This warning is displayed once per session. 
4: In file(file, "rt") :   cannot open file 'lefse.res': No such file or directory Called from: file(file, "rt")
--
Browse[1]> | Browse[1]>
Browse[1]>


Unfortunatly, I can solve the problem.

I am using R in windows.

Thank you so much

**Comment by ying14** [comment]
As the error states, it is having trouble finding the lefse scripts. Have you downloaded them and placed them where they can be accessed? Try placing them in your working directory.

**Comment by negin1986** [comment]
Hello,
I get the following error when I run lefse2 function:

Traceback (most recent call last):
  File "run_lefse.py", line 4, in <module>
    from lefse import *
  File "/Users/neginvalizadegan/Desktop/All_Files/PhD-related/Brinkworth_Lab/MyDissertation/Data_Analysis/Microbiome/JFB_New_March042019_Fluidigm_20190304/QIIME2_16SrRNA/R_codes/Defense_R/nsegata-lefse-9adc3a62460e/lefse.py", line 3, in <module>
    import rpy2.robjects as robjects
ImportError: No module named rpy2.robjects
[1] "Wrote lefse.res"
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: select_() is deprecated. 
Please use select() instead

**Comment by tkalhan** [comment]
Hello, I am dentist with no experience in coding/R. I am working on a project requiring LEfSe analysis. 
I am trying to run the LEfSe analysis by converting phyloseq object to lefse format, but I get the below error.
Could someone kindly advise how to resolve this? 
I only have the dplyr package loaded as suggested above. 
 

>physeq1.NRBrel 
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 398 taxa and 1933 samples ]
sample_data() Sample Data:       [ 1933 samples by 56 sample variables ]
tax_table()   Taxonomy Table:    [ 398 taxa by 6 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 398 tips and 397 internal nodes ]

> lefse.tbl <- lefse2(physeq1.NRBrel,class="M24_ICDAS_dichotomized")
`summarise()` regrouping output by 'sample', 'taxon' (override with `.groups` argument)
`summarise()` regrouping output by 'sample', 'taxon' (override with `.groups` argument)
`summarise()` regrouping output by 'sample', 'taxon' (override with `.groups` argument)
`summarise()` regrouping output by 'sample', 'taxon' (override with `.groups` argument)
`summarise()` regrouping output by 'sample', 'taxon' (override with `.groups` argument)
`summarise()` regrouping output by 'sample', 'taxon' (override with `.groups` argument) 

Error in dcast(., sample ~ taxon, value.var = "pctseqs", fill = 0) : 
  could not find function "dcast" 
8.function_list[[i]](value) 
7.freduce(value, `_function_list`) 
6.`_fseq`(`_lhs`) 
5.eval(quote(`_fseq`(`_lhs`)), env, env) 
4.eval(quote(`_fseq`(`_lhs`)), env, env) 
3.withVisible(eval(quote(`_fseq`(`_lhs`)), env, env)) 
2.otu.levels %>% dcast(sample ~ taxon, value.var = "pctseqs", fill = 0) %>% 
    left_join(samp, by = "sample") %>% select_(.dots = c(keepvars, 
    lazyeval::interp(~everything()))) 
1.lefse2(physeq1.NRBrel, class = "M24_ICDAS_dichotomized") 

Thank you for your kind help!

**Comment by Justice-Lu** [comment]
The link for adding lefse to $PATH  and the link for downloading the lefse zip file is not accessible for me..  
Can someone please point me to the right direction for where to download the lefse zip again ?? 

Thanks !

**Comment by ying14** [comment]
Try here: [https://github.com/SegataLab/lefse](https://github.com/SegataLab/lefse)
