### ISSUE TITLE
Lefse issues in R

### ISSUE THREAD

**Issue by amyzf** [ying14/yingtools2#17]
Hello!

I am trying to use lefse in R and keep getting the following error message. It seems like lefse was installed ok- when I type system2(lefse, args = "--version") I get back
"biom, version 2.1.7"

Error message:
lefse <- py_run_file("/Users/amyzf/miniconda3/envs/lefse-env/bin/run_lefse.py", local=FALSE) # 
Error in py_run_file_impl(file, local, convert) : 
  TabError: inconsistent use of tabs and spaces in indentation (<string>, line 25)

Thank you!

**Comment by ying14** [comment]
Can't be certain but it looks like you installed lefse through a conda image, and are now trying to run using the reticulate package? Would need more details about what you are trying to do in the above code. In general, I would make sure you can successfully execute run_lefse.py script from command line, as a reality-check, before trying to interface it in R.

In any event, the lefse wrapper function in yingtools2 does not go through conda or reticulate, it just tries to run the script locally via system call. So if you intended to use the wrapper function later on, it may be necessary to do a more direct install.

**Comment by amyzf** [comment]
Yes- that is what I was trying to do. It seems like lefse is running ok in command line. I have a newer version of python on my computer (v 3.7) so had to create a new environment (lefse-env) w/ python v 2.7 and then put it there. 

I can see the run_lefse file in /Users/amyzf/miniconda3/envs/lefse-env/bin/run_lefse.py but am still confused about how to port this to R, which is why I was trying going through reticulate.

Thank you!
