### ISSUE TITLE
ifultools error during install

### ISSUE THREAD

**Issue by FilipeMatteoli** [ying14/yingtools2#19]
Hello, during installation I came across this error:

```
ERROR: dependency ‘ifultools’ is not available for package ‘yingtools2’
Error: Failed to install 'yingtools2' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpK30RZj/file32ed6d922f9f/yingtools2_0.0.1.22.tar.gz’ had non-zero exit status
```

I checked the status of this package here https://cran.r-project.org/web/packages/ifultools/index.html . And says it has been removed, I am proceeding with a manual install of ifultools which version should I choose?

Best,

**Comment by mdoolin2014** [comment]
Hello, I am getting the same error. Any information would be helpful. Thank you!

```
Downloading GitHub repo ying14/yingtools2@master
Skipping 1 packages not available: ifultools
Installing 7 packages: ifultools, coxphf, logistf, xlsx, rJava, mice, xlsxjars
Error: Failed to install 'yingtools2' from GitHub:
    (converted from warning) package ‘ifultools’ is not available (for R version 4.0.1)
````

**Comment by ying14** [comment]
The package needs to install ifultools, but looks like it's no long available and has been restructured. I removed the dependency from the yingtools2 package.... try re-installing.

**Comment by mdoolin2014** [comment]
Hi Ying, Yes, it worked, thank you!
