### ISSUE TITLE
lefse

### ISSUE THREAD

**Issue by AlexandreThibodeauUdM** [ying14/yingtools2#2]
Hello!
I was trying to find R packages to use LEFSE on a phyloseq object and you seem to have the answer!

However, when I try to run it I get the following error. I am using R studio on windows.

lefse(sandrine_echant_seuls_rarefy, class="Site")

[1] "Wrote lefse.res"
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: Column `sample` joining factor and character vector, coercing into character vector 
2: running command 'format_input.py lefse.txt lefse.in -c 1   -o 1000000' had status 127 
3: running command 'run_lefse.py lefse.in lefse.res -a 0.05 -w 0.05 -l 2 -e 0 -y 0 -s 0' had status 127 
4: In file(file, "rt") :
  cannot open file 'lefse.res': No such file or directory

Thanks you!

**Comment by ying14** [comment]
Hi alexthibodeau,
Unfortunately the function requires that you install LEFSE python scripts (from the bioBakery repo) and can run them from command line. This works well for me on Linux, but my understanding is that these scripts don't run perfectly on Windows and/or Mac, and require some sort of tweaking to make it work. Good luck... admittedly the function is still a work in progress and remains reliant on the original old python script.

**Comment by elittmann** [comment]
I've added a page on our wiki on how to use the wrapper `lefse` function in yingtools2, I hope it is helpful!

https://github.com/ying14/yingtools2/wiki/Using-the-%60lefse%60-wrapper-function

Thanks
