### ISSUE TITLE
Error in file(file, "rt") : cannot open the connection

### ISSUE THREAD

**Issue by Sarsi1411** [ying14/yingtools2#21]
Hello,

I am trying to run the lefse2 function and I encounter this error below,

python: can't open file 'format_input.py': [Errno 2] No such file or directory
python: can't open file 'run_lefse.py': [Errno 2] No such file or directory
[1] "Wrote lefse.res"
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'lefse.res': No such file or directory

I am not sure, how to address this. Could someone help me, please?
Thanks in advance
Sarsi

**Comment by elittmann** [comment]
Hi Sarsi,

That function is a wrapper for the lefse python scripts that aren't included in this R package-- you'd need to have lefse installed locally to run it. Lefse is tricky to locally install on newer machines though... I'd recommend using docker to run lefse:
https://github.com/SegataLab/lefse

Thanks,
-Eric
