### ISSUE TITLE
Cannot find nsegata-lefse zip file

### ISSUE THREAD

**Issue by klv501** [ying14/yingtools2#22]
Hello, 

I am trying to download the dependency nsegata-lefse zip file to run an lefse analysis in R, however the link provided on the page is not working to download the zip, or the link for the installation instructions for $PATH installation. Would you be able to provide this file/link please?

Thanks

**Comment by elittmann** [comment]
lefse has since been updated to python3 and can be installed via [conda](https://github.com/SegataLab/lefse). the lefse functions in yingtools2 are R wrapper functions that rely on being able to run the core lefse python scripts from your $PATH
