### ISSUE TITLE
send.text.message

### ISSUE THREAD

**Issue by susanapsilva** [ying14/yingtools2#24]
When I run the function it gives me an error. I used my portuguese number to try.
Thanks a lot

send.text.message(message="Hello", number = "+351XXXXXXXXX")
Error in send.text.message(message = "Hello", number = "+351XXXXXXXXX") : 
  YTError: Not sure how to handle this operating system: Windows
Go tell Ying about this.

**Comment by ying14** [comment]
The message is because you are using an operating system other than linux. But unfortunately this function does not work any more. It used textbelt.com to issue texts, but now you have to pay to use that service. I am not aware of any free text service that might be usable in this situation.
