### ISSUE TITLE
lefse function can't not run

### ISSUE THREAD

**Issue by pwang16** [ying14/yingtools2#5]
Hi Ying,

Could you please get me know to to use phyloseq data to obtain the lefse results of CID94_lefse.png?

I run the "lefse.tbl <- lefse(cid94,class="Patient_ID",subclass="day")" as you show in the example, but it doesn't work.

Thanks a lot,
Peng

**Comment by ying14** [comment]
Right now this function requires you to have a working version of lefse.py installed, which needs to be executable. So essentially this is just a wrapper function for the python script which you can obtain from BitBucket: [https://bitbucket.org/nsegata/lefse/downloads/](url)
