### ISSUE TITLE
Problem with python + R on Mac

### ISSUE THREAD

**Issue by rachelkaminsky2691** [ying14/yingtools2#6]
Hello,
I am interested in using your package for some of my analyses, but in trying to get python and R to communicate with each other (i.e. install rpy2, which I assume you have to do to use your package) I kept getting errors which seem to be related to trying to do this in newer versions of Mac OSX + newer versions of R.

I can see from one of the older issues that you use Linux, so not sure if you would have heard about this issue/would know how to fix it, but just thought I'd bring it up in case the package is still being developed. Thanks!

-Rachel

**Comment by ying14** [comment]
Hi Rachel,
Yes this is definitely a work in progress. The package does not use rpy2 but one function, lefse, calls lefse.py as a terminal command. Basically if you can run lefse.py from command line (i.e. it is installed and executable), it is supposed to work.

**Comment by rachelkaminsky2691** [comment]
hmm I have lefse installed and can run from terminal, but I get errors in R saying it can't find the appropriate lefse commands. I also downloaded the zip you link to (though the name is slightly different-- nsegata-lefse-82605a2ae7b7--not sure if that would mean anything) and get other errors regarding rpy2. Maybe I'm just missing something....

**Comment by ying14** [comment]
Ok then it sounds like it may be an issue with the lefse script installation itself, which does use rpy2, I believe. It could be that the script isn't executable or does not lie on $PATH. 

Basically, if you can open a terminal and run the commands shown in the HMP example in the lefse bitbucket page, then the function ought to work.
[https://bitbucket.org/biobakery/biobakery/wiki/lefse#rst-header-lefse-brew-docker-vm](https://bitbucket.org/biobakery/biobakery/wiki/lefse#rst-header-lefse-brew-docker-vm)
