### ISSUE TITLE
Lefse2 issue

### ISSUE THREAD

**Issue by ddehita** [ying14/yingtools2#7]
Hello,

I'm a PhD student working on microbiome data. I found your LEfSe wrapper when I looked for an R way to carry out an LDA  analysis. I have tried your function (the modification when you don't have $PATH access), but I received the next error message from R:

**Traceback (most recent call last):
  File "run_lefse.py", line 4, in <module>
    from lefse import *
  File "/Users/macbookpro/Desktop/Microbiomes/nsegata-lefse-82605a2ae7b7/lefse.py", line 3, in <module>
    import rpy2.robjects as robjects
ImportError: No module named rpy2.robjects
[1] "Wrote lefse.res"
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: Column `sample` joining factor and character vector, coercing into character vector 
2: In file(file, "rt") :
  cannot open file 'lefse.res': No such file or directory
Called from: file(file, "rt")**

How can I solve this problem?

Thanks in advance and thank you for developing this code.
Regards,

David

**Comment by elittmann** [comment]
Looks like you are missing the rpy2 module from python. Are you able to call run_lefse.py in a terminal window outside of R in that directory?

If you get the same error try installing the rpy2 module: 
pip install rpy2

**Comment by nhungdoan1905** [comment]
@elittmann when I call run_lefse.py in a terminal window outside of R  I got a problem: 
File "/Users/Bioinformatics/Downloads/nsegata-lefse-9adc3a62460e/run_lefse.py", line 66
    print "Testing feature",str(nf),": ",feat_name,
                          ^
SyntaxError: invalid syntax
what should I do?

**Comment by DrMaestre** [comment]
I have the same issue. I installed the rpy2 module successfully. Installed Python 2.7 too. Not sure how to solve this. Any help appreciated (MacOS el capitan).
